### ISSUE TITLE
[Cloud Docker] Static files not available if these are created on build stage

### ISSUE THREAD

**Issue by sorinsugar** [magento/ece-tools#587]
I don't know if this issue should be reported here, but is seems like an ece-tools probem.
We've tested 3 different approaches using magento cloud docker on local (production mode) and one of them fails to deploy the static files correctly.
We've installed magento 2.3.2 using all steps from documentation, first time with no config.php and no .magento.env.yaml configurations and it worked ok, magento website was loading, all js/css files were present.
The second time, we've added a confg.php (using ece-tools config:dump command after the first try) and a .magento.env.yaml file in which we've added the following code:
```
stage:
  build:
    SCD_STRATEGY: "compact"
    SCD_THREADS: 1
    SCD_MATRIX:
      "Magento/luma":
        language:
          - en_US
      "Magento/backend":
        language:
          - en_US
```
After running all the required commands, the website returned a fatal error (var/report error) stating that the deployed_version.txt file was not found. While checking the fpm container, we've found that pub/static folder was empty and init/pub/static folder contents were wrong:
```
ssugar@sorin-sugar:~/Projects/magento-cloud-2.3.2$ docker exec -it magento-cloud-232_fpm_1 bash
root@a96f2d1c9e5e:/var/www/html# ls -al /app/pub/static
total 8
drwxrwxr-x 2 root root 4096 Aug  9 06:35 .
drwxrwxr-x 6 1000 1000 4096 Aug  9 06:35 ..
root@a96f2d1c9e5e:/var/www/html# ls -al /app/init/pub/static/
total 8
drwxr-xr-x 2 root root 4096 Aug  9 06:35 .
drwxr-xr-x 4 root root 4096 Aug  9 06:35 ..
lrwxrwxrwx 1 root root   30 Aug  9 06:35 .htaccess -> /app/init/pub/static/.htaccess
lrwxrwxrwx 1 root root   30 Aug  9 06:35 adminhtml -> /app/init/pub/static/adminhtml
lrwxrwxrwx 1 root root   25 Aug  9 06:35 base -> /app/init/pub/static/base
lrwxrwxrwx 1 root root   41 Aug  9 06:35 deployed_version.txt -> /app/init/pub/static/deployed_version.txt
lrwxrwxrwx 1 root root   29 Aug  9 06:35 frontend -> /app/init/pub/static/frontend
```
The third approach was using the following .magento.env.yaml file
```
stage:
  build:
    SKIP_SCD: true
  deploy:
    SCD_STRATEGY: "compact"
    SCD_THREADS: 1
    SCD_MATRIX:
      "Magento/luma":
        language:
          - en_US
      "Magento/backend":
        language:
          - en_US
```
This worked as expected and the static files were found. It is worth mentioning that we've run docker-sync clean after each run.

### Preconditions
1. Docker version 19.03.1, build 74b1e89e8a
2. docker-compose version 1.24.1, build 4667896
3. docker-sync 0.5.11
4. Latest magento cloud docker images
5. Operating system Ubuntu 16.04

### Steps to reproduce
1. Clone magento-cloud repo for 2.3.2
2. Add the files attached to this issue [samples.zip](https://github.com/magento/ece-tools/files/3485207/samples.zip)
3. Run the following commands
```
docker-sync start
docker-compose up -d
docker-compose run --rm build cloud-build
docker-compose run --rm deploy cloud-deploy
docker-compose run --rm deploy magento-command config:set system/full_page_cache/caching_application 2
docker-compose run --rm deploy magento-command cache:flush
```

### Expected result
1. The fpm container should have static files inside /app/pub/static and website should work

### Actual result
1. The /app/pub/static folder is empty on fpm container and the site fails with a fatal error
