### ISSUE TITLE
[ECE-TOOLS] Add "store" to WARM_UP_PAGES logic

### ISSUE THREAD

**Issue by Bodyanuk** [magento/ece-tools#615]
### Problem
It's impossible to preload cache for multiple stores.

### Requirements
1. At least **2 Store Views**
2. Configuration "**Add store code to URL**" enabled
2. Preload cache for next URLs
```
https://example.com/store_code1/full/path/to/page.html
https://example.com/store_code2/full/path/to/page.html
```
**Where:**
https://example.com/ - `{base_url}`
store_code1 - `{store_code}|{store_id}`
full/path/to/page.html - `any path to page`

### Configuration
```
stage:
    post-deploy:
        WARM_UP_PAGES:
            - "full/path/to/any/page.html"
```

### Actual result
Preload cache for `default` Store View only.

### Expected result
Preload cache for all/specified Store Views.

### Proposal
Add new type to configuration. I prefer to use **store_code** instead **store_id** because store_id can be different on environments.
```
stage:
    post-deploy:
        WARM_UP_PAGES:
            - "store:store_code:full/path/to/any/page.html"
            - "store:store_code1|store_code2|store_code3|:full/path/to/any/page.html"
            - "store:*:full/path/to/any/page.html"
```
1. Preload cache for 1 specific Store View
2. Preload cache for couple of specific Store Views
3. Preload cache for all active Store Views
