### ISSUE TITLE
[ECE-TOOLS] Add "products" to WARM_UP_PAGES logic

### ISSUE THREAD

**Issue by Bodyanuk** [magento/ece-tools#616]
### Problem
It's impossible to preload cache for specific products.
Marketing department usually uses specific products in commercial. So, it would be great to have already cached product pages. 
Of course, this feature must have some limits.

### Proposal
```
stage:
    post-deploy:
        WARM_UP_PAGES:
            - "products:store_code:sku1"
            - "products:*:sku1|sku2|sku3"
            - "products:store_code|store_code2:*"
```
1. Preload cache for product with **SKU = sku1** and **Store View code = store_code**
2. Preload cache for product with **SKU in (sku1, sku2, sku3)** for **all Store Views**
3. Preload cache for **all enabled products** for **multiple Store Views** 

I recommend add limits to **"products:*:*"** pattern and show information in build log about it:
> You reached N products urls limit
